### ISSUE TITLE
BREAKING: Version 1.6.4 breaks the login

### ISSUE THREAD

**Issue by jacotec** [element-hq/element-x-ios#2817]
### Steps to reproduce

1. After update to version 1.6.4 log out
2. Try to log back in to the server
3. After entering the server URL proceed to the next screen (summary)
4. Pressing "continue" immediately gives the error message attached below (normally the MAS welcome screen would load here)

Reverting to 1.6.3 fixes the login!

![image](https://github.com/element-hq/element-x-ios/assets/3321655/08ffd520-f528-47b7-bdb2-ba97733bcd19)

#### What did you expect?

I should be able to log into my server

#### What happened instead?

See above

### Your phone model

iPhone 14 Pro Max, iPad Pro M2

### Operating system version

IOS / iPadOS 17.4.1

### Application version

1.6.4

### Homeserver

Synapse 1.106.0

### Will you send logs?

Yes

**Comment by jacotec** [comment]
Thanks to @pixlwave in the EX chatroom I found the issue which caused this:

The "issuer:" config in Synapse was missing a trailing slash which seems to be important now from 1.6.4:

```
experimental_features:
  msc3861:
    enabled: true

    # Synapse will call `{issuer}/.well-known/openid-configuration` to get the OIDC configuration
    issuer: https://auth.mydomain.de/

```

Closing the issue.
